import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { Prisma, ServiceStatus } from "@prisma/client";

import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import {
  normalizePreferredTimeWindowSlug,
  resolvePreferredTimeWindowLabel,
} from "@/lib/time-window";
import { getZonedWeekday, SERVICE_TIME_ZONE } from "@/lib/timezone";

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ jobId: string }> },
) {
  const session = await getServerSession(authOptions);
  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { jobId } = await params;
  if (!jobId) {
    return NextResponse.json({ error: "Job ID required" }, { status: 400 });
  }

  const orgId = (session.user as any)?.orgId ?? null;

  let payload: any = null;
  try {
    payload = await request.json();
  } catch (error) {
    return NextResponse.json({ error: "Invalid JSON payload" }, { status: 400 });
  }

  if (!payload || typeof payload !== "object") {
    return NextResponse.json({ error: "Invalid payload" }, { status: 400 });
  }

  const { scheduledDate, preferredTimeWindowSlug } = payload as {
    scheduledDate?: string;
    preferredTimeWindowSlug?: string | null;
  };

  if (!scheduledDate || typeof scheduledDate !== "string") {
    return NextResponse.json({ error: "scheduledDate is required" }, { status: 400 });
  }

  const scheduled = new Date(scheduledDate);
  if (Number.isNaN(scheduled.getTime())) {
    return NextResponse.json({ error: "Invalid scheduledDate" }, { status: 400 });
  }

  const job = await prisma.job.findFirst({
    where: {
      id: jobId,
      ...(orgId ? { orgId } : {}),
    },
    select: {
      id: true,
      orgId: true,
      customerId: true,
      serviceVisits: {
        orderBy: { scheduledDate: "desc" },
        take: 1,
        select: {
          serviceType: true,
          yardSize: true,
          dogsServiced: true,
          metadata: true,
          deodorize: true,
          litterService: true,
          scheduledEnd: true,
          routeStop: {
            select: {
              estimatedArrival: true,
              scheduledArrival: true,
            },
          },
        },
      },
    },
  });

  if (!job) {
    return NextResponse.json({ error: "Job not found" }, { status: 404 });
  }

  const template = job.serviceVisits[0];
  if (!template) {
    return NextResponse.json(
      {
        error:
          "Unable to infer visit details for this job. Create the first visit through onboarding or dispatch.",
      },
      { status: 400 },
    );
  }

  const slug = normalizePreferredTimeWindowSlug(preferredTimeWindowSlug ?? undefined);
  const preferredLabel = slug
    ? resolvePreferredTimeWindowLabel(slug, null)
    : null;

  const metadata: Prisma.JsonObject = template.metadata && typeof template.metadata === "object"
    ? { ...(template.metadata as Prisma.JsonObject) }
    : {};

  if (slug) {
    metadata.preferredTimeWindowSlug = slug;
    metadata.preferredTimeWindow = preferredLabel ?? slug;
  }

  const visitDurationMs = template.scheduledEnd
    ? template.scheduledEnd.getTime() - scheduled.getTime()
    : null;

  const createdVisit = await prisma.serviceVisit.create({
    data: {
      orgId: job.orgId,
      customerId: job.customerId,
      jobId: job.id,
      serviceType: template.serviceType,
      yardSize: template.yardSize,
      dogsServiced: template.dogsServiced,
      status: ServiceStatus.SCHEDULED,
      scheduledDate: scheduled,
      scheduledEnd:
        visitDurationMs && visitDurationMs > 0
          ? new Date(scheduled.getTime() + visitDurationMs)
          : null,
      metadata,
      preferredTimeWindowSlug: slug ?? null,
      preferredTimeWindow: preferredLabel,
      deodorize: template.deodorize,
      litterService: template.litterService,
      autoGenerated: false,
    },
    include: {
      assignedTo: {
        select: { id: true, name: true },
      },
    },
  });

  await refreshJobNextVisit(job.id);

  return NextResponse.json({
    visit: {
      id: createdVisit.id,
      scheduledDate: createdVisit.scheduledDate.toISOString(),
      status: createdVisit.status,
      preferredTimeWindowSlug: createdVisit.preferredTimeWindowSlug,
      preferredTimeWindow: createdVisit.preferredTimeWindow,
      assignedTo: createdVisit.assignedTo
        ? {
            id: createdVisit.assignedTo.id,
            name: createdVisit.assignedTo.name,
          }
        : null,
    },
  });
}

async function refreshJobNextVisit(jobId: string) {
  const nextVisit = await prisma.serviceVisit.findFirst({
    where: {
      jobId,
      status: {
        in: [ServiceStatus.SCHEDULED, ServiceStatus.IN_PROGRESS],
      },
    },
    orderBy: { scheduledDate: "asc" },
  });

  await prisma.job.update({
    where: { id: jobId },
    data: {
      nextVisitAt: nextVisit?.scheduledDate ?? null,
      dayOfWeek: nextVisit?.scheduledDate
        ? getZonedWeekday(nextVisit.scheduledDate, SERVICE_TIME_ZONE)
        : null,
    },
  });
}
