module.exports = {
  apps: [
    {
      name: 'insightscoop',
      script: 'npm',
      args: 'start',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '30s',
      restart_delay: 5000,
      exp_backoff_restart_delay: 100,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000
      }
    },
    {
      name: 'worker-billing',
      script: 'npx',
      args: 'tsx jobs/start-billing-automation.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-customer-email-reports',
      script: 'npx',
      args: 'tsx jobs/start-customer-email-reports.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-geo-snapshot',
      script: 'npx',
      args: 'tsx jobs/start-geo-snapshot-worker.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-media-analysis',
      script: 'npx',
      args: 'tsx jobs/start-media-analysis-worker.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-offer-auto-assign',
      script: 'npx',
      args: 'tsx jobs/start-marketplace-offer-auto-assign.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-offer-sweeper',
      script: 'npx',
      args: 'tsx jobs/start-marketplace-offer-sweeper.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-offers',
      script: 'npx',
      args: 'tsx jobs/start-marketplace-offers.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-outbound-cadence',
      script: 'npx',
      args: 'tsx jobs/start-outbound-cadence-worker.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-outbound-sla',
      script: 'npx',
      args: 'tsx jobs/start-outbound-sla-worker.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-outbound-transcription',
      script: 'npx',
      args: 'tsx jobs/start-outbound-transcription-worker.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-payout-release',
      script: 'npx',
      args: 'tsx jobs/start-payout-release.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-push-notifications',
      script: 'npx',
      args: 'tsx jobs/start-push-notifications.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-quickbooks',
      script: 'npx',
      args: 'tsx jobs/start-quickbooks-sync.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-route-drafts',
      script: 'npx',
      args: 'tsx jobs/start-route-drafts-worker.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-tile-generation',
      script: 'npx',
      args: 'tsx jobs/start-tile-generation-worker.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-tile-publish',
      script: 'npx',
      args: 'tsx jobs/start-tile-publish-worker.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-visit-generator',
      script: 'npx',
      args: 'tsx jobs/start-visit-generator-worker.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-visit-summary',
      script: 'npx',
      args: 'tsx jobs/start-visit-summary-worker.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    },
    {
      name: 'worker-wellness-embeddings',
      script: 'npx',
      args: 'tsx jobs/start-wellness-embeddings.ts',
      cwd: '/var/www/insightscoop',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      restart_delay: 10000
    }
  ]
};
