import { beforeEach, describe, expect, it, vi } from "vitest";
import { Frequency } from "@prisma/client";

const prismaMock = vi.hoisted(() => ({
  serviceVisit: {
    create: vi.fn(),
    findFirst: vi.fn(),
  },
  job: {
    update: vi.fn(),
  },
}));

const enqueueVisitGenerationMock = vi.hoisted(() => vi.fn());

vi.mock("@/lib/prisma", () => ({
  prisma: prismaMock,
}));

vi.mock("@/lib/jobs/serviceVisitGenerator", () => ({
  enqueueVisitGeneration: enqueueVisitGenerationMock,
}));

vi.mock("@/lib/dispatch/visit-generator", () => ({
  generateServiceVisits: vi.fn().mockResolvedValue([]),
}));

describe("scheduleInitialVisitForJob", () => {
  let scheduleInitialVisitForJob: typeof import("@/lib/dispatch/auto-schedule").scheduleInitialVisitForJob;

  beforeEach(async () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2025-03-01T00:00:00Z"));
    vi.clearAllMocks();

    ({ scheduleInitialVisitForJob } = await import("@/lib/dispatch/auto-schedule"));
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it.each<{ frequency: Frequency; expected: number }>([
    { frequency: Frequency.ONE_TIME, expected: 1 },
    { frequency: Frequency.WEEKLY, expected: 28 },
    { frequency: Frequency.BI_WEEKLY, expected: 56 },
    { frequency: Frequency.TWICE_WEEKLY, expected: 28 },
    { frequency: Frequency.DAILY, expected: 28 },
    { frequency: Frequency.MONTHLY, expected: 90 },
  ])("enqueues lookahead days for $frequency jobs", async ({ frequency, expected }) => {
    const baseDate = new Date("2025-04-01T14:00:00Z");

    prismaMock.serviceVisit.create.mockResolvedValue({
      id: `visit_${frequency}`,
      scheduledDate: baseDate,
      status: "SCHEDULED",
    } as any);
    prismaMock.serviceVisit.findFirst.mockResolvedValue(null);
    prismaMock.job.update.mockResolvedValue({});

    await scheduleInitialVisitForJob({
      orgId: "org",
      jobId: `job_${frequency}`,
      customerId: "cust",
      frequency,
      preferredStartDate: baseDate,
      yardSizeHint: "medium",
      dogsCount: 1,
      metadata: {},
      primaryUserId: "user",
      billingPreference: "weekly",
      revenueCents: 2500,
    });

    expect(enqueueVisitGenerationMock).toHaveBeenCalledWith(
      expect.objectContaining({
        orgId: "org",
        lookAheadDays: expected,
      }),
    );
  });

  it("uses the frequency-based lookahead when enqueueing generation", async () => {
    const baseDate = new Date("2025-04-01T14:00:00Z");

    prismaMock.serviceVisit.create.mockResolvedValue({
      id: "visit_initial",
      scheduledDate: baseDate,
      status: "SCHEDULED",
    } as any);
    prismaMock.serviceVisit.findFirst.mockResolvedValue(null);
    prismaMock.job.update.mockResolvedValue({});

    await scheduleInitialVisitForJob({
      orgId: "org",
      jobId: "job_weekly",
      customerId: "cust",
      frequency: "WEEKLY",
      preferredStartDate: baseDate,
      yardSizeHint: "medium",
      dogsCount: 1,
      metadata: {},
      primaryUserId: "user",
      billingPreference: "monthly",
      revenueCents: 2500,
    });

    expect(enqueueVisitGenerationMock).toHaveBeenCalledWith(
      expect.objectContaining({
        orgId: "org",
        lookAheadDays: 28,
      }),
    );
  });

  it("creates a trial follow-up visit for twice-weekly jobs", async () => {
    const baseDate = new Date("2025-04-01T14:00:00Z"); // Use future date to avoid the while loop issue

    const firstVisit = {
      id: "visit_initial",
      scheduledDate: baseDate,
      status: "SCHEDULED",
    } as any;

    prismaMock.serviceVisit.create
      .mockResolvedValueOnce(firstVisit)
      .mockResolvedValue({ id: "visit_follow", scheduledDate: new Date("2025-04-04T14:00:00Z") } as any);

    prismaMock.serviceVisit.findFirst.mockResolvedValue(null);
    prismaMock.job.update.mockResolvedValue({});

    await scheduleInitialVisitForJob({
      orgId: "org",
      jobId: "job_twice",
      customerId: "cust",
      frequency: "TWICE_WEEKLY",
      preferredStartDate: baseDate,
      yardSizeHint: "medium",
      dogsCount: 2,
      metadata: {},
      primaryUserId: "user",
      billingPreference: "weekly",
      revenueCents: 4500,
      trialEndsAt: new Date("2025-04-08T00:00:00Z"),
      trialLengthDays: 7,
    });

    expect(prismaMock.serviceVisit.create).toHaveBeenCalledTimes(2);
    const followUpCall = prismaMock.serviceVisit.create.mock.calls[1]?.[0];
    expect(followUpCall.data.autoGenerated).toBe(true);

    const jobUpdateCall = prismaMock.job.update.mock.calls.at(-1);
    expect(jobUpdateCall).toBeTruthy();
    const nextVisitAt = jobUpdateCall?.[0].data?.nextVisitAt;
    expect(nextVisitAt).toBeInstanceOf(Date);
    if (nextVisitAt instanceof Date) {
      const diffDays = Math.round(
        (nextVisitAt.getTime() - baseDate.getTime()) / (1000 * 60 * 60 * 24),
      );
      expect(diffDays).toBe(7);
    }
  });

  it.each<{ frequency: Frequency; expectedDays?: number | null; expectedMonths?: number }>([
    { frequency: Frequency.ONE_TIME, expectedDays: null },
    { frequency: Frequency.WEEKLY, expectedDays: 7 },
    { frequency: Frequency.BI_WEEKLY, expectedDays: 14 },
    { frequency: Frequency.TWICE_WEEKLY, expectedDays: 10 },
    { frequency: Frequency.DAILY, expectedDays: 8 },
    { frequency: Frequency.MONTHLY, expectedMonths: 1 },
  ])("sets nextVisitAt based on cadence for $frequency", async ({ frequency, expectedDays, expectedMonths }) => {
    const baseDate = new Date("2025-04-01T14:00:00Z");

    prismaMock.serviceVisit.create.mockResolvedValue({
      id: `visit_${frequency}`,
      scheduledDate: baseDate,
      status: "SCHEDULED",
    } as any);
    prismaMock.serviceVisit.findFirst.mockResolvedValue(null);
    prismaMock.job.update.mockResolvedValue({});

    await scheduleInitialVisitForJob({
      orgId: "org",
      jobId: `job_${frequency}`,
      customerId: "cust",
      frequency,
      preferredStartDate: baseDate,
      yardSizeHint: "medium",
      dogsCount: 1,
      metadata: {},
      primaryUserId: "user",
      billingPreference: "weekly",
      revenueCents: 2500,
    });

    const jobUpdateCall = prismaMock.job.update.mock.calls.at(-1);
    const nextVisitAt = jobUpdateCall?.[0].data?.nextVisitAt ?? null;

    if (expectedDays === null) {
      expect(nextVisitAt).toBeNull();
      return;
    }

    expect(nextVisitAt).toBeInstanceOf(Date);
    if (nextVisitAt instanceof Date) {
      if (typeof expectedMonths === "number") {
        expect(nextVisitAt.getMonth()).toBe((baseDate.getMonth() + expectedMonths) % 12);
      } else {
        const diffDays = Math.round(
          (nextVisitAt.getTime() - baseDate.getTime()) / (1000 * 60 * 60 * 24),
        );
        expect(diffDays).toBe(expectedDays);
      }
    }
  });

  it("seeds weekday follow-ups during the trial for daily jobs", async () => {
    const baseDate = new Date("2025-04-01T09:00:00Z"); // Use future date to avoid the while loop issue
    const trialEndsAt = new Date("2025-04-08T00:00:00Z");

    const firstVisit = {
      id: "visit_daily_initial",
      scheduledDate: baseDate,
      status: "SCHEDULED",
    } as any;

    prismaMock.serviceVisit.create
      .mockResolvedValueOnce(firstVisit)
      .mockResolvedValue({} as any);

    prismaMock.serviceVisit.findFirst.mockResolvedValue(null);
    prismaMock.job.update.mockResolvedValue({});

    await scheduleInitialVisitForJob({
      orgId: "org",
      jobId: "job_daily",
      customerId: "cust",
      frequency: "DAILY",
      preferredStartDate: baseDate,
      yardSizeHint: "medium",
      dogsCount: 1,
      metadata: {},
      primaryUserId: "user",
      billingPreference: "weekly",
      revenueCents: 2500,
      trialEndsAt,
      trialLengthDays: 7,
    });

    // Initial visit + four weekday follow-ups
    expect(prismaMock.serviceVisit.create).toHaveBeenCalledTimes(5);

    const jobUpdateCall = prismaMock.job.update.mock.calls.at(-1);
    const nextVisitAt = jobUpdateCall?.[0].data?.nextVisitAt;
    expect(nextVisitAt).toBeInstanceOf(Date);
    if (nextVisitAt instanceof Date) {
      const weekday = nextVisitAt.getUTCDay();
      expect([1, 2, 3, 4, 5]).toContain(weekday);
      expect(nextVisitAt.getTime()).toBeGreaterThanOrEqual(trialEndsAt.getTime());
    }
  });

  it("includes weekend follow-ups when weekend coverage is enabled", async () => {
    const baseDate = new Date("2025-04-01T09:00:00Z");

    const firstVisit = {
      id: "visit_daily_weekend_initial",
      scheduledDate: baseDate,
      status: "SCHEDULED",
    } as any;

    prismaMock.serviceVisit.create
      .mockResolvedValueOnce(firstVisit)
      .mockResolvedValue({} as any);

    prismaMock.serviceVisit.findFirst.mockResolvedValue(null);
    prismaMock.job.update.mockResolvedValue({});

    await scheduleInitialVisitForJob({
      orgId: "org",
      jobId: "job_daily_weekend",
      customerId: "cust",
      frequency: "DAILY",
      preferredStartDate: baseDate,
      yardSizeHint: "medium",
      dogsCount: 1,
      metadata: {},
      primaryUserId: "user",
      billingPreference: "weekly",
      revenueCents: 2500,
      trialEndsAt: new Date("2025-04-08T00:00:00Z"),
      trialLengthDays: 7,
      weekendUpgrade: true,
    });

    // Initial visit + six additional follow-ups (Mon–Sun coverage)
    expect(prismaMock.serviceVisit.create).toHaveBeenCalledTimes(7);
  });
});





