import { prisma } from "@/lib/prisma";
import { info } from "@/lib/log";
import { Prisma } from "@prisma/client";
import {
  CertificationType,
  Frequency,
  ServiceStatus,
  ServiceType,
  YardSize,
} from "@prisma/client";
import {
  resolveSubsequentVisitDate,
  startOfDay,
  addDays,
} from "./frequency";
import {
  enqueueVisitGeneration,
} from "@/lib/jobs/serviceVisitGenerator";
import { generateServiceVisits } from "@/lib/dispatch/visit-generator";
import { extractPreferredTimeWindow } from "@/lib/time-window";
import {
  constructZonedDate,
  convertUtcToZonedParts,
  getZonedWeekday,
  SERVICE_TIME_ZONE,
} from "@/lib/timezone";

const VISIT_GENERATION_LOOKAHEAD_DAYS: Record<Frequency, number> = {
  ONE_TIME: 1,
  WEEKLY: 28,
  BI_WEEKLY: 56,
  TWICE_WEEKLY: 28,
  DAILY: 28,
  MONTHLY: 90,
};

function resolveVisitGenerationHorizonDays(frequency: Frequency): number {
  return VISIT_GENERATION_LOOKAHEAD_DAYS[frequency] ?? 28;
}

function normalizeYardSize(value?: string | null): YardSize {
  switch ((value || "medium").toLowerCase()) {
    case "small":
      return YardSize.SMALL;
    case "large":
      return YardSize.LARGE;
    case "xlarge":
    case "xl":
      return YardSize.XLARGE;
    default:
      return YardSize.MEDIUM;
  }
}

function deriveServiceType(frequency: Frequency): ServiceType {
  return frequency === "ONE_TIME" ? ServiceType.ONE_TIME : ServiceType.REGULAR;
}

export async function scheduleInitialVisitForJob(options: {
  orgId: string;
  jobId: string;
  customerId: string;
  frequency: Frequency;
  preferredStartDate?: Date | null;
  techniciansSuggestedId?: string | null;
  backupTechnicianId?: string | null;
  tileId?: string | null;
  requiredCertificationTypes?: CertificationType[] | null;
  yardSizeHint?: string | null;
  dogsCount?: number | null;
  metadata?: Record<string, unknown> | null;
  primaryUserId?: string | null;
  billingPreference?: "monthly" | "weekly";
  revenueCents?: number | null;
  trialEndsAt?: Date | null;
  trialLengthDays?: number | null;
  weekendUpgrade?: boolean;
}) {
  const {
    orgId,
    jobId,
    customerId,
    frequency,
    preferredStartDate,
    techniciansSuggestedId,
    backupTechnicianId,
    tileId,
    requiredCertificationTypes,
    yardSizeHint,
    dogsCount,
    metadata,
    primaryUserId,
    billingPreference,
    revenueCents,
    trialEndsAt,
    trialLengthDays,
    weekendUpgrade,
  } = options;

  const now = new Date();
  const baseDate = preferredStartDate
    ? new Date(preferredStartDate)
    : new Date(now);

  if (preferredStartDate) {
    baseDate.setSeconds(0, 0);
  } else {
    baseDate.setHours(9, 0, 0, 0);
  }

  let targetDate = baseDate;
  let dayOfWeek = getZonedWeekday(targetDate);

  while (targetDate < now && frequency !== "ONE_TIME") {
    targetDate = resolveSubsequentVisitDate(targetDate, frequency, dayOfWeek);
    dayOfWeek = getZonedWeekday(targetDate);
  }

  const { label: metadataWindowLabel, slug: metadataWindowSlug } =
    extractPreferredTimeWindow(metadata ?? null);

  const visit = await prisma.serviceVisit.create({
    data: {
      orgId,
      customerId,
      jobId,
      userId: primaryUserId ?? null,
      scheduledDate: targetDate,
      status: ServiceStatus.SCHEDULED,
      serviceType: deriveServiceType(frequency),
      yardSize: normalizeYardSize(yardSizeHint),
      dogsServiced: Math.max(1, dogsCount ?? 1),
      assignedToId: techniciansSuggestedId ?? null,
      backupAssignedToId: backupTechnicianId ?? null,
      autoGenerated: false,
      metadata: metadata == null ? Prisma.JsonNull : (metadata as any),
      tileId: tileId ?? null,
      requiredCertifications:
        requiredCertificationTypes && requiredCertificationTypes.length > 0
          ? (requiredCertificationTypes as unknown as Prisma.InputJsonValue)
          : Prisma.JsonNull,
      revenueCents: typeof revenueCents === "number" ? revenueCents : null,
      preferredTimeWindow: metadataWindowLabel ?? null,
      preferredTimeWindowSlug: metadataWindowSlug ?? null,
    },
  });

  const dayOfWeekFinal = getZonedWeekday(visit.scheduledDate);
  const nextVisitBase =
    frequency === "ONE_TIME"
      ? null
      : resolveSubsequentVisitDate(targetDate, frequency, dayOfWeekFinal);

  const nextVisit = nextVisitBase
    ? (() => {
        const nextParts = convertUtcToZonedParts(nextVisitBase);
        const visitParts = convertUtcToZonedParts(visit.scheduledDate);
        return constructZonedDate(
          nextParts.year,
          nextParts.month,
          nextParts.day,
          visitParts.hour,
          visitParts.minute,
          visitParts.second,
          0,
          SERVICE_TIME_ZONE,
        );
      })()
    : null;

  const trialSeed = await seedTrialFollowUpVisits({
    orgId,
    jobId,
    customerId,
    frequency,
    baseVisit: visit,
    techniciansSuggestedId,
    backupTechnicianId,
    yardSizeHint,
    dogsCount,
    metadata,
    primaryUserId,
    tileId: tileId ?? null,
    requiredCertificationTypes: requiredCertificationTypes ?? null,
    revenueCents,
    preferredWindow: {
      label: metadataWindowLabel,
      slug: metadataWindowSlug,
    },
    dayOfWeek: dayOfWeekFinal,
    trialEndsAt,
    trialLengthDays,
    weekendUpgrade,
  });

  const effectiveNextVisit = trialSeed?.nextVisitAt ?? nextVisit;

  await prisma.job.update({
    where: { id: jobId },
    data: {
      dayOfWeek: dayOfWeekFinal,
      nextVisitAt: effectiveNextVisit ?? null,
      ...(typeof tileId !== "undefined" ? { tileId: tileId ?? null } : {}),
      ...(typeof revenueCents === "number"
        ? { perVisitRevenueCents: revenueCents }
        : {}),
      ...(metadataWindowLabel
        ? { preferredTimeWindow: metadataWindowLabel }
        : {}),
      ...(metadataWindowSlug
        ? { preferredTimeWindowSlug: metadataWindowSlug }
        : {}),
    },
  });

  const generationHorizonDays = (() => {
    return resolveVisitGenerationHorizonDays(frequency);
  })();

  const generationWindowStart = startOfDay(targetDate);

  await enqueueVisitGeneration({
    orgId,
    date: generationWindowStart.toISOString(),
    lookAheadDays: generationHorizonDays,
  });

  try {
    await generateServiceVisits({
      orgId,
      jobIds: [jobId],
      date: generationWindowStart,
      lookAheadDays: generationHorizonDays,
      jobLimit: 50,
    });
  } catch (error) {
    console.warn("[dispatch] immediate visit generation failed", error);
  }

  info("dispatch.scheduleInitial", {
    jobId,
    frequency,
    weekendUpgrade,
    billingPreference,
    trialFollowUpsCreated: trialSeed?.createdCount ?? 0,
    trialFollowUpsReused: trialSeed?.reusedCount ?? 0,
    firstVisitId: visit.id,
    nextVisitAt: effectiveNextVisit?.toISOString() ?? null,
  });

  return visit;
}

async function seedTrialFollowUpVisits(options: {
  orgId: string;
  jobId: string;
  customerId: string;
  frequency: Frequency;
  baseVisit: Awaited<ReturnType<typeof prisma.serviceVisit.create>>;
  techniciansSuggestedId?: string | null;
  backupTechnicianId?: string | null;
  yardSizeHint?: string | null;
  dogsCount?: number | null;
  metadata?: Record<string, unknown> | null;
  primaryUserId?: string | null;
  tileId?: string | null;
  requiredCertificationTypes?: CertificationType[] | null;
  revenueCents?: number | null;
  preferredWindow?: { label?: string | null; slug?: string | null };
  dayOfWeek: number;
  trialEndsAt?: Date | null;
  trialLengthDays?: number | null;
  weekendUpgrade?: boolean;
}): Promise<{ nextVisitAt: Date | null; createdCount: number; reusedCount: number } | null> {
  const {
    orgId,
    jobId,
    customerId,
    frequency,
    baseVisit,
    techniciansSuggestedId,
    backupTechnicianId,
    yardSizeHint,
    dogsCount,
    metadata,
    primaryUserId,
    tileId,
    requiredCertificationTypes,
    revenueCents,
    preferredWindow,
    dayOfWeek,
    trialEndsAt,
    trialLengthDays,
    weekendUpgrade,
  } = options;

  if (frequency !== Frequency.TWICE_WEEKLY && frequency !== Frequency.DAILY) {
    return null;
  }

  const baseDate = new Date(baseVisit.scheduledDate);
  const trialWindowEnd = (() => {
    if (trialEndsAt) return new Date(trialEndsAt);
    if (typeof trialLengthDays === "number" && trialLengthDays > 0) {
      const clone = new Date(baseDate);
      clone.setDate(clone.getDate() + trialLengthDays);
      return clone;
    }
    const defaultWindow = new Date(baseDate);
    defaultWindow.setDate(defaultWindow.getDate() + 7);
    return defaultWindow;
  })();

  let lastScheduledDate = new Date(baseDate);
  let iterations = 0;
  const maxIterations = frequency === Frequency.DAILY ? 10 : 4;

  const requiredCertsJson =
    requiredCertificationTypes && requiredCertificationTypes.length > 0
      ? (requiredCertificationTypes as unknown as Prisma.InputJsonValue)
      : Prisma.JsonNull;

  const preferredLabel = preferredWindow?.label ?? null;
  const preferredSlug = preferredWindow?.slug ?? null;

  const skipWeekends = frequency === Frequency.DAILY && !weekendUpgrade;

  let createdCount = 0;
  let reusedCount = 0;

  while (iterations < maxIterations) {
    let candidateDate = resolveSubsequentVisitDate(
      lastScheduledDate,
      frequency,
      dayOfWeek,
    );

    if (candidateDate > trialWindowEnd) {
      break;
    }

    if (skipWeekends) {
      let weekday = getZonedWeekday(candidateDate, SERVICE_TIME_ZONE);
      while (weekday === 0 || weekday === 6) {
        candidateDate = addDays(candidateDate, 1);
        if (candidateDate > trialWindowEnd) {
          return { nextVisitAt: null, createdCount, reusedCount };
        }
        weekday = getZonedWeekday(candidateDate, SERVICE_TIME_ZONE);
      }
    }

    const existing = await prisma.serviceVisit.findFirst({
      where: {
        jobId,
        scheduledDate: {
          gte: startOfDay(candidateDate),
          lt: addDays(startOfDay(candidateDate), 1),
        },
        status: {
          in: [
            ServiceStatus.SCHEDULED,
            ServiceStatus.IN_PROGRESS,
            ServiceStatus.COMPLETED,
          ],
        },
      },
    });

    const nextScheduled = existing
      ? new Date(existing.scheduledDate)
      : (() => {
          const candidateWithTime = new Date(candidateDate);
          const baseParts = convertUtcToZonedParts(baseVisit.scheduledDate);
          const candidateParts = convertUtcToZonedParts(candidateDate);
          return constructZonedDate(
            candidateParts.year,
            candidateParts.month,
            candidateParts.day,
            baseParts.hour,
            baseParts.minute,
            baseParts.second,
            0,
            SERVICE_TIME_ZONE,
          );
        })();

    if (!existing) {
      await prisma.serviceVisit.create({
        data: {
          orgId,
          customerId,
          jobId,
          userId: primaryUserId ?? null,
          scheduledDate: nextScheduled,
          status: ServiceStatus.SCHEDULED,
          serviceType: deriveServiceType(frequency),
          yardSize: normalizeYardSize(yardSizeHint),
          dogsServiced: Math.max(1, dogsCount ?? 1),
          assignedToId: techniciansSuggestedId ?? null,
          backupAssignedToId: backupTechnicianId ?? null,
          autoGenerated: true,
          metadata: metadata == null ? Prisma.JsonNull : (metadata as any),
          tileId: tileId ?? null,
          requiredCertifications: requiredCertsJson,
          revenueCents: typeof revenueCents === "number" ? revenueCents : null,
          preferredTimeWindow: preferredLabel ?? null,
          preferredTimeWindowSlug: preferredSlug ?? null,
        },
      });
      createdCount += 1;
    } else {
      reusedCount += 1;
    }

    lastScheduledDate = nextScheduled;
    iterations += 1;
  }

  if (iterations === 0) {
    if (createdCount || reusedCount) {
      return { nextVisitAt: null, createdCount, reusedCount };
    }
    return null;
  }

  let nextVisitDate = resolveSubsequentVisitDate(
    lastScheduledDate,
    frequency,
    dayOfWeek,
  );

  if (skipWeekends) {
    let weekday = getZonedWeekday(nextVisitDate, SERVICE_TIME_ZONE);
    while (weekday === 0 || weekday === 6) {
      nextVisitDate = addDays(nextVisitDate, 1);
      weekday = getZonedWeekday(nextVisitDate, SERVICE_TIME_ZONE);
    }
  }

  const nextWithTime = new Date(nextVisitDate);
  const timeParts = convertUtcToZonedParts(baseVisit.scheduledDate);
  const nextParts = convertUtcToZonedParts(nextVisitDate);
  const nextVisitAt = constructZonedDate(
    nextParts.year,
    nextParts.month,
    nextParts.day,
    timeParts.hour,
    timeParts.minute,
    timeParts.second,
    0,
    SERVICE_TIME_ZONE,
  );

  return { nextVisitAt, createdCount, reusedCount };
}
