import { ServiceTileStatus } from "@prisma/client";

type ServiceWindowSlot = "AM" | "PM" | "FULL";

export interface ServiceWindowSeed {
  weekday: number;
  window: ServiceWindowSlot;
  maxStops: number;
}

export interface TileSeed {
  slug: string;
  name: string;
  status: ServiceTileStatus;
  minCertifiedScoopers: number;
  minCustomerUnits: number;
  coverageRadiusMeters?: number;
  serviceWindows: ServiceWindowSeed[];
  notes?: string;
}

const makeWindow = (
  weekday: number,
  window: ServiceWindowSlot,
  maxStops: number,
): ServiceWindowSeed => ({
  weekday,
  window,
  maxStops,
});

const MAJOR_CITY_TILE_SEEDS: TileSeed[] = [
  {
    slug: "minneapolis-central",
    name: "Minneapolis – Central & Northeast",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 4,
    minCustomerUnits: 60,
    coverageRadiusMeters: 3600,
    serviceWindows: [
      makeWindow(1, "AM", 60),
      makeWindow(4, "PM", 60),
    ],
    notes:
      "Downtown high-rises, North Loop, Marcy-Holmes, and Northeast arts district corridors.",
  },
  {
    slug: "minneapolis-south",
    name: "Minneapolis – South & Nokomis",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 4,
    minCustomerUnits: 58,
    coverageRadiusMeters: 3600,
    serviceWindows: [
      makeWindow(2, "AM", 58),
      makeWindow(5, "PM", 58),
    ],
    notes:
      "Powderhorn, Nokomis, Standish, and Longfellow single-family corridors heavy with daily plans.",
  },
  {
    slug: "minneapolis-north",
    name: "Minneapolis – North & Camden",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 46,
    coverageRadiusMeters: 3400,
    serviceWindows: [
      makeWindow(1, "PM", 46),
      makeWindow(4, "AM", 46),
    ],
    notes: "Camden, Near North, Bryn Mawr, and Victory neighborhoods with alley access focus.",
  },
  {
    slug: "minneapolis-lakes-southwest",
    name: "Minneapolis – Lakes & Southwest",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 4,
    minCustomerUnits: 52,
    coverageRadiusMeters: 3200,
    serviceWindows: [
      makeWindow(3, "AM", 52),
      makeWindow(6, "AM", 40),
    ],
    notes:
      "Linden Hills, Kenwood, Uptown, Fulton, and Lynnhurst lake homes with premium add-ons.",
  },
  {
    slug: "bloomington-west",
    name: "Bloomington – West 169",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 45,
    coverageRadiusMeters: 3200,
    serviceWindows: [
      makeWindow(1, "AM", 45),
      makeWindow(4, "PM", 45),
    ],
    notes: "West Bloomington cul-de-sacs near Hyland and Normandale Lake.",
  },
  {
    slug: "bloomington-east",
    name: "Bloomington – East River",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 45,
    coverageRadiusMeters: 3200,
    serviceWindows: [
      makeWindow(2, "AM", 45),
      makeWindow(5, "PM", 45),
    ],
    notes: "East Bloomington river valley, Old Shakopee corridor, MSP adjacent blocks.",
  },
  {
    slug: "brooklyn-park-north",
    name: "Brooklyn Park – North Mississippi",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 42,
    coverageRadiusMeters: 3200,
    serviceWindows: [
      makeWindow(2, "PM", 42),
      makeWindow(5, "AM", 42),
    ],
    notes: "River North, Oxbow Creek, and Edinbrook neighborhoods with larger yards.",
  },
  {
    slug: "brooklyn-park-south",
    name: "Brooklyn Park – Zane & 85th",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 40,
    coverageRadiusMeters: 3000,
    serviceWindows: [
      makeWindow(1, "AM", 40),
      makeWindow(3, "PM", 40),
    ],
    notes: "Southern Brooklyn Park, Noble, Zanewood, and Autumn Ridge.",
  },
  {
    slug: "maple-grove-northwest",
    name: "Maple Grove – Northwest Lakes",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 38,
    coverageRadiusMeters: 3400,
    serviceWindows: [
      makeWindow(1, "PM", 38),
      makeWindow(4, "AM", 38),
    ],
    notes: "Fish Lake, Weaver Lake, and Fernbrook areas with haul-away demand.",
  },
  {
    slug: "maple-grove-southeast",
    name: "Maple Grove – Arbor Lakes",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 40,
    coverageRadiusMeters: 3000,
    serviceWindows: [
      makeWindow(2, "AM", 40),
      makeWindow(5, "PM", 40),
    ],
    notes: "Arbor Lakes townhomes, Maple Grove Crossing, Maple Ridge industrial fringe.",
  },
  {
    slug: "plymouth-east",
    name: "Plymouth – Medicine Lake Loop",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 38,
    coverageRadiusMeters: 3000,
    serviceWindows: [
      makeWindow(1, "AM", 38),
      makeWindow(4, "PM", 38),
    ],
    notes: "Medicine Lake, Parkers Lake, and east Plymouth townhome clusters.",
  },
  {
    slug: "plymouth-west",
    name: "Plymouth – West Lakeland",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 36,
    coverageRadiusMeters: 3200,
    serviceWindows: [
      makeWindow(2, "PM", 36),
      makeWindow(5, "AM", 36),
    ],
    notes: "Wayzata High School corridor, Terra Vista, and Providence Academy neighborhoods.",
  },
  {
    slug: "minnetonka-east",
    name: "Minnetonka – Ridgedale & Glen Lake",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 34,
    coverageRadiusMeters: 3000,
    serviceWindows: [
      makeWindow(1, "AM", 34),
      makeWindow(4, "PM", 34),
    ],
    notes: "Ridgedale retail halo, Glen Lake, Groveland elementary neighborhoods.",
  },
  {
    slug: "minnetonka-west",
    name: "Minnetonka – Excelsior Blvd West",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 32,
    coverageRadiusMeters: 3200,
    serviceWindows: [
      makeWindow(2, "AM", 32),
      makeWindow(5, "PM", 32),
    ],
    notes: "Deephaven border, Clear Springs, Scenic Heights, Lake Minnetonka feeders.",
  },
  {
    slug: "eden-prairie-north",
    name: "Eden Prairie – Anderson Lakes",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 36,
    coverageRadiusMeters: 3200,
    serviceWindows: [
      makeWindow(1, "PM", 36),
      makeWindow(4, "AM", 36),
    ],
    notes: "Northeast Eden Prairie, Anderson Lakes, Preserve, and Eden Ridge HOA corridors.",
  },
  {
    slug: "eden-prairie-south",
    name: "Eden Prairie – Bluff Creek & Flying Cloud",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 34,
    coverageRadiusMeters: 3600,
    serviceWindows: [
      makeWindow(2, "PM", 34),
      makeWindow(5, "AM", 34),
    ],
    notes: "Southwest Eden Prairie acre lots, Flying Cloud airport fringe, Mitchell Lake.",
  },
  {
    slug: "edina-north",
    name: "Edina – 50th & France",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 32,
    coverageRadiusMeters: 2800,
    serviceWindows: [
      makeWindow(1, "AM", 32),
      makeWindow(4, "PM", 32),
    ],
    notes: "Country Club, Morningside, Lexington, and Grandview neighborhoods.",
  },
  {
    slug: "edina-south",
    name: "Edina – Centennial Lakes",
    status: ServiceTileStatus.WAITLIST,
    minCertifiedScoopers: 3,
    minCustomerUnits: 32,
    coverageRadiusMeters: 2800,
    serviceWindows: [
      makeWindow(2, "AM", 32),
      makeWindow(5, "PM", 32),
    ],
    notes: "South Edina around Centennial Lakes, Creek Valley, and Braemar HOA clusters.",
  },
];

interface SingleCitySeedConfig {
  slug: string;
  name: string;
  weekday: number;
  window: ServiceWindowSlot;
  maxStops: number;
  minCertifiedScoopers: number;
  minCustomerUnits: number;
  coverageRadiusMeters?: number;
  notes: string;
  secondaryWindow?: {
    weekday: number;
    window: ServiceWindowSlot;
    maxStops: number;
  };
}

const SINGLE_CITY_BASE: SingleCitySeedConfig[] = [
  {
    slug: "brooklyn-center-core",
    name: "Brooklyn Center",
    weekday: 2,
    window: "AM",
    maxStops: 32,
    minCertifiedScoopers: 2,
    minCustomerUnits: 28,
    coverageRadiusMeters: 2600,
    notes: "Shingle Creek, Palmer Lake, Earle Brown, and Humboldt Greenway blocks.",
    secondaryWindow: { weekday: 5, window: "PM", maxStops: 28 },
  },
  {
    slug: "champlin-mississippi",
    name: "Champlin",
    weekday: 3,
    window: "PM",
    maxStops: 26,
    minCertifiedScoopers: 2,
    minCustomerUnits: 24,
    coverageRadiusMeters: 3000,
    notes: "Mississippi Point, Champlin Shores, and West River Road neighborhoods.",
  },
  {
    slug: "crystal-central",
    name: "Crystal",
    weekday: 2,
    window: "AM",
    maxStops: 28,
    minCertifiedScoopers: 2,
    minCustomerUnits: 26,
    coverageRadiusMeters: 2400,
    notes: "Bass Lake Road, Brownwood, Lee Park, and Welcome Park corridors.",
    secondaryWindow: { weekday: 4, window: "PM", maxStops: 24 },
  },
  {
    slug: "dayton-river",
    name: "Dayton",
    weekday: 2,
    window: "PM",
    maxStops: 20,
    minCertifiedScoopers: 2,
    minCustomerUnits: 18,
    coverageRadiusMeters: 3600,
    notes: "Dayton River Road, Sundance Woods, and Diamond Lake new builds (Hennepin portion).",
  },
  {
    slug: "deephaven-lakeside",
    name: "Deephaven",
    weekday: 3,
    window: "AM",
    maxStops: 20,
    minCertifiedScoopers: 1,
    minCustomerUnits: 16,
    coverageRadiusMeters: 2200,
    notes: "Cottagewood, Deephaven Heights, and Thorpe Lane lakefront clients.",
  },
  {
    slug: "excelsior-downtown",
    name: "Excelsior",
    weekday: 4,
    window: "PM",
    maxStops: 18,
    minCertifiedScoopers: 1,
    minCustomerUnits: 14,
    coverageRadiusMeters: 2000,
    notes: "Water Street, College Lake, and Maynard's marina-adjacent homes.",
  },
  {
    slug: "golden-valley-core",
    name: "Golden Valley",
    weekday: 2,
    window: "AM",
    maxStops: 30,
    minCertifiedScoopers: 2,
    minCustomerUnits: 28,
    coverageRadiusMeters: 2600,
    notes: "Tyrol Hills, Bassett Creek, General Mills campus neighborhoods.",
    secondaryWindow: { weekday: 5, window: "AM", maxStops: 24 },
  },
  {
    slug: "greenfield-rural",
    name: "Greenfield",
    weekday: 3,
    window: "AM",
    maxStops: 18,
    minCertifiedScoopers: 1,
    minCustomerUnits: 14,
    coverageRadiusMeters: 4800,
    notes: "Lake Sarah, Pioneer Trail estates, and rolling acreage (Hennepin portion).",
  },
  {
    slug: "greenwood-lakes",
    name: "Greenwood",
    weekday: 3,
    window: "PM",
    maxStops: 14,
    minCertifiedScoopers: 1,
    minCustomerUnits: 12,
    coverageRadiusMeters: 1800,
    notes: "Lafayette Bay and St. Alban's Bay waterfront lots.",
  },
  {
    slug: "hanover-southfork",
    name: "Hanover",
    weekday: 4,
    window: "AM",
    maxStops: 16,
    minCertifiedScoopers: 1,
    minCustomerUnits: 12,
    coverageRadiusMeters: 4200,
    notes: "Southfork River Bluff and Crow River neighborhoods inside Hennepin lines.",
  },
  {
    slug: "hopkins-downtown",
    name: "Hopkins",
    weekday: 3,
    window: "AM",
    maxStops: 26,
    minCertifiedScoopers: 2,
    minCustomerUnits: 24,
    coverageRadiusMeters: 2200,
    notes: "Downtown Hopkins, Blake Road Corridor, Nine Mile Creek townhomes.",
    secondaryWindow: { weekday: 5, window: "PM", maxStops: 20 },
  },
  {
    slug: "independence-pioneer",
    name: "Independence",
    weekday: 4,
    window: "PM",
    maxStops: 18,
    minCertifiedScoopers: 1,
    minCustomerUnits: 14,
    coverageRadiusMeters: 5200,
    notes: "Pioneer Creek, Lake Independence peninsula, and sprawling hobby farms.",
  },
  {
    slug: "long-lake-corridor",
    name: "Long Lake",
    weekday: 3,
    window: "AM",
    maxStops: 18,
    minCertifiedScoopers: 1,
    minCustomerUnits: 14,
    coverageRadiusMeters: 2000,
    notes: "Long Lake shoreline, Old Long Lake Road, and Wayzata Boulevard homes.",
  },
  {
    slug: "loretto-hamlet",
    name: "Loretto",
    weekday: 5,
    window: "AM",
    maxStops: 12,
    minCertifiedScoopers: 1,
    minCustomerUnits: 10,
    coverageRadiusMeters: 1800,
    notes: "Downtown Loretto, Saints Peter & Paul, and west metro acreage pocket.",
  },
  {
    slug: "maple-plain-trail",
    name: "Maple Plain",
    weekday: 2,
    window: "PM",
    maxStops: 16,
    minCertifiedScoopers: 1,
    minCustomerUnits: 12,
    coverageRadiusMeters: 2600,
    notes: "Old Maple Plain, Lake Katrina, and Baker Park adjacent neighborhoods.",
  },
  {
    slug: "medicine-lake-ring",
    name: "Medicine Lake",
    weekday: 3,
    window: "PM",
    maxStops: 14,
    minCertifiedScoopers: 1,
    minCustomerUnits: 12,
    coverageRadiusMeters: 1600,
    notes: "City of Medicine Lake peninsula and surrounding parkland homes.",
  },
  {
    slug: "minnetonka-beach-spit",
    name: "Minnetonka Beach",
    weekday: 4,
    window: "AM",
    maxStops: 12,
    minCertifiedScoopers: 1,
    minCustomerUnits: 10,
    coverageRadiusMeters: 1800,
    notes: "Historic Lafayette Club spit with gated lake estates.",
  },
  {
    slug: "minnetrista-northshore",
    name: "Minnetrista",
    weekday: 4,
    window: "PM",
    maxStops: 24,
    minCertifiedScoopers: 2,
    minCustomerUnits: 20,
    coverageRadiusMeters: 5200,
    notes: "Northshore estates, Halstead Bay, Woodland Cove master plan (Hennepin section).",
  },
  {
    slug: "mound-westonka",
    name: "Mound",
    weekday: 3,
    window: "PM",
    maxStops: 22,
    minCertifiedScoopers: 2,
    minCustomerUnits: 18,
    coverageRadiusMeters: 2600,
    notes: "Three Points, Surfside, and Grandview Boulevard peninsulas.",
  },
  {
    slug: "new-hope-center",
    name: "New Hope",
    weekday: 2,
    window: "AM",
    maxStops: 28,
    minCertifiedScoopers: 2,
    minCustomerUnits: 26,
    coverageRadiusMeters: 2200,
    notes: "Civic Center Park, Meadow Lake, and Bass Creek areas.",
    secondaryWindow: { weekday: 4, window: "PM", maxStops: 22 },
  },
  {
    slug: "orono-northshore",
    name: "Orono",
    weekday: 3,
    window: "AM",
    maxStops: 24,
    minCertifiedScoopers: 2,
    minCustomerUnits: 20,
    coverageRadiusMeters: 3600,
    notes: "Crystal Bay, Fox Street, and Orono School district peninsulas.",
  },
  {
    slug: "osseo-mainstreet",
    name: "Osseo",
    weekday: 2,
    window: "PM",
    maxStops: 16,
    minCertifiedScoopers: 1,
    minCustomerUnits: 12,
    coverageRadiusMeters: 1600,
    notes: "Central Osseo grid, Elm Creek, and Jefferson Highway corridors.",
  },
  {
    slug: "richfield-core",
    name: "Richfield",
    weekday: 1,
    window: "PM",
    maxStops: 32,
    minCertifiedScoopers: 2,
    minCustomerUnits: 30,
    coverageRadiusMeters: 2400,
    notes: "South Minneapolis border, Wood Lake, and Penn-South loops.",
    secondaryWindow: { weekday: 4, window: "AM", maxStops: 28 },
  },
  {
    slug: "robbinsdale-lakeview",
    name: "Robbinsdale",
    weekday: 2,
    window: "PM",
    maxStops: 24,
    minCertifiedScoopers: 2,
    minCustomerUnits: 20,
    coverageRadiusMeters: 2000,
    notes: "Lakeview Terrace, Victory Memorial, and Crystal Lake frontage.",
  },
  {
    slug: "rogers-gateway",
    name: "Rogers",
    weekday: 2,
    window: "PM",
    maxStops: 24,
    minCertifiedScoopers: 2,
    minCustomerUnits: 20,
    coverageRadiusMeters: 4200,
    notes: "Hassan area, Fletcher Hills, and I-94 logistics neighborhoods (Hennepin portion).",
    secondaryWindow: { weekday: 5, window: "AM", maxStops: 20 },
  },
  {
    slug: "shorewood-south",
    name: "Shorewood",
    weekday: 4,
    window: "PM",
    maxStops: 20,
    minCertifiedScoopers: 1,
    minCustomerUnits: 16,
    coverageRadiusMeters: 2400,
    notes: "Christmas Lake, Badger Park, and Shorewood Oaks peninsulas.",
  },
  {
    slug: "spring-park-channel",
    name: "Spring Park",
    weekday: 5,
    window: "AM",
    maxStops: 14,
    minCertifiedScoopers: 1,
    minCustomerUnits: 12,
    coverageRadiusMeters: 1800,
    notes: "West Arm, Lakeview Terrace, and channel homes between Mound and Orono.",
  },
  {
    slug: "st-anthony-northeast",
    name: "St. Anthony",
    weekday: 1,
    window: "AM",
    maxStops: 24,
    minCertifiedScoopers: 2,
    minCustomerUnits: 20,
    coverageRadiusMeters: 2200,
    notes: "Village of St. Anthony inside Hennepin, Silver Lake Road and Kenzie Terrace.",
  },
  {
    slug: "st-bonifacius-enclave",
    name: "St. Bonifacius",
    weekday: 4,
    window: "PM",
    maxStops: 14,
    minCertifiedScoopers: 1,
    minCustomerUnits: 12,
    coverageRadiusMeters: 2000,
    notes: "Hennepin enclave community between Minnetrista and Carver County.",
  },
  {
    slug: "st-louis-park-core",
    name: "St. Louis Park",
    weekday: 1,
    window: "PM",
    maxStops: 30,
    minCertifiedScoopers: 2,
    minCustomerUnits: 28,
    coverageRadiusMeters: 2400,
    notes: "West End, Birchwood, Aquila, and Fern Hill neighborhoods.",
    secondaryWindow: { weekday: 4, window: "AM", maxStops: 26 },
  },
  {
    slug: "tonka-bay-marina",
    name: "Tonka Bay",
    weekday: 3,
    window: "PM",
    maxStops: 14,
    minCertifiedScoopers: 1,
    minCustomerUnits: 12,
    coverageRadiusMeters: 1800,
    notes: "Gideon's Bay, Libbs Lake, and Tonka Bay Marina peninsulas.",
  },
  {
    slug: "wayzata-downtown",
    name: "Wayzata",
    weekday: 3,
    window: "AM",
    maxStops: 20,
    minCertifiedScoopers: 2,
    minCustomerUnits: 18,
    coverageRadiusMeters: 2200,
    notes: "Lake Street, Wayzata Highlands, and Bushaway Road estates.",
  },
  {
    slug: "woodland-peninsula",
    name: "Woodland",
    weekday: 3,
    window: "PM",
    maxStops: 12,
    minCertifiedScoopers: 1,
    minCustomerUnits: 10,
    coverageRadiusMeters: 1600,
    notes: "Windsor, Breezy Point, and Gale Road peninsula estates.",
  },
  {
    slug: "corcoran-pioneer",
    name: "Corcoran",
    weekday: 2,
    window: "AM",
    maxStops: 22,
    minCertifiedScoopers: 2,
    minCustomerUnits: 18,
    coverageRadiusMeters: 4200,
    notes: "Pioneer Trail corridor, Bellwether, and Corcoran downtown acreage.",
  },
  {
    slug: "medina-hamel",
    name: "Medina",
    weekday: 2,
    window: "PM",
    maxStops: 26,
    minCertifiedScoopers: 2,
    minCustomerUnits: 22,
    coverageRadiusMeters: 4200,
    notes: "Hamel, Medina Morningside, Fields of Medina, and Medina Country Club.",
    secondaryWindow: { weekday: 5, window: "AM", maxStops: 20 },
  },
  {
    slug: "rockford-prairie",
    name: "Rockford",
    weekday: 5,
    window: "PM",
    maxStops: 16,
    minCertifiedScoopers: 1,
    minCustomerUnits: 12,
    coverageRadiusMeters: 3600,
    notes: "Crow River, Prairie Island, and Hennepin-side neighborhoods.",
  },
];

const HENNEPIN_TILE_SEEDS: TileSeed[] = [
  ...MAJOR_CITY_TILE_SEEDS,
  ...SINGLE_CITY_BASE.map((city) => {
    const windows = [makeWindow(city.weekday, city.window, city.maxStops)];
    if (city.secondaryWindow) {
      windows.push(
        makeWindow(
          city.secondaryWindow.weekday,
          city.secondaryWindow.window,
          city.secondaryWindow.maxStops,
        ),
      );
    }

    return {
      slug: city.slug,
      name: city.name,
      status: ServiceTileStatus.WAITLIST,
      minCertifiedScoopers: city.minCertifiedScoopers,
      minCustomerUnits: city.minCustomerUnits,
      coverageRadiusMeters: city.coverageRadiusMeters,
      serviceWindows: windows,
      notes: city.notes,
    } satisfies TileSeed;
  }),
];

export { MAJOR_CITY_TILE_SEEDS, HENNEPIN_TILE_SEEDS };
